name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Cypress repo
      - name: Checkout Cypress repo
        uses: actions/checkout@v3

      # 2. Install Cypress dependencies (🔥 FIX)
      - name: Install Cypress dependencies
        run: npm install

      # 3. Clone backend
      - name: Clone backend
        run: git clone https://github.com/sameepabadhuge/QuizMaster-backend.git

      # 4. Clone frontend
      - name: Clone frontend
        run: git clone https://github.com/sameepabadhuge/QuizMaster-frontend.git

      # 5. Backend setup
      - name: Install backend
        working-directory: QuizMaster-backend
        run: npm install

      - name: Start backend
        working-directory: QuizMaster-backend
        run: npm start &

      # 6. Frontend setup
      - name: Install frontend
        working-directory: QuizMaster-frontend
        run: npm install

      - name: Start frontend
        working-directory: QuizMaster-frontend
        run: npm run dev &

      # 7. Wait for app
      - name: Wait for frontend
        run: npx wait-on http://localhost:3000

      # 8. Run Cypress
      - name: Run Cypress
        run: npx cypress run