name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Cypress repo
      - name: Checkout Cypress repo
        uses: actions/checkout@v3

      # 2. Clone Backend Repo
      - name: Clone backend
        run: git clone https://github.com/sameepabadhuge/QuizMaster-backend.git

      # 3. Clone Frontend Repo
      - name: Clone frontend
        run: git clone https://github.com/sameepabadhuge/QuizMaster-frontend.git

      # 4. Install backend dependencies
      - name: Install backend
        working-directory: QuizMaster-backend
        run: npm install

      # 5. Start backend
      - name: Start backend
        working-directory: QuizMaster-backend
        run: npm start &

      # 6. Install frontend dependencies
      - name: Install frontend
        working-directory: QuizMaster-frontend
        run: npm install

      # 7. Start frontend
      - name: Start frontend
        working-directory: QuizMaster-frontend
        run: npm run dev &

      # 8. Wait until frontend is ready
      - name: Wait for frontend
        run: npx wait-on http://localhost:3000

      # 9. Run Cypress tests
      - name: Run Cypress
        run: npx cypress run